modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Mithion/Mystic-Alchemy/issues"

[[mods]]
modId="mysticalchemy"
version="0.0.4"
displayName="Mystic Alchemy"
credits="Thanks to the M&A community for helping me with ideas"
authors="Mithion"
description='''
Expands potions and brewing in the game to be more dynamic, and magical.
'''

[[dependencies.mysticalchemy]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.mysticalchemy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
